apiVersion: v1
kind: Pod
metadata:
  annotations:
    enfabrica.net/license: license-sample/9
    enfabrica.net/icense: license-sample/9
    license.enfabrica.net: license-sample/9
  creationTimestamp: null
  labels:
    run: nginx2
  name: nginx3
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  