apiVersion: v1
kind: Pod
metadata:
  annotations:
    enfabrica.net/license: license-sample/2
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  